// THE ATTRIBUTION PAGE'S CONTENT (build-plan step 30 / M10, v3-D24).
//
// ---------------------------------------------------------------------------
// WHY THIS PAGE IS A LEGAL OBLIGATION, NOT A COURTESY
// ---------------------------------------------------------------------------
// BUILD-PLAN's launch-checklist gate names "QAC/Tanzil attribution page live",
// and v3-D24 closes with "Attribution page ships regardless" — regardless,
// specifically, of whether the morphology is stripped from the shipped bundle.
//
// The reason it is unconditional: the Quranic Arabic Corpus is GPL-licensed,
// and this product is a paid, closed bundle. Stripping the annotations from the
// learner artifact reduces the DISTRIBUTION question; it does not retire the
// ATTRIBUTION requirement, because the corpus was still used to build what is
// being sold. Every distractor in the product was generated by consulting QAC
// morphology. A page that appeared only if some other check failed would be
// exactly the wrong shape.
//
// ---------------------------------------------------------------------------
// EVERY FACT HERE WAS VERIFIED AGAINST THE VENDORED SOURCE, NOT RECALLED
// ---------------------------------------------------------------------------
// The source of truth is `v1/data/raw/SOURCES.md`, which records what was
// actually vendored, from where, and under what licence. Version numbers,
// attribution names and licence names below are copied from there rather than
// from memory, because an attribution page that misattributes is worse than
// none: it is a false statement about someone else's work.
//
// WHAT IS DELIBERATELY NOT CLAIMED HERE:
//   - No claim that the Quran text is licensed by anyone. It is not — the text
//     may be copied and distributed verbatim, and SOURCES.md says exactly that.
//     The licence discussion concerns the ANNOTATIONS only.
//   - No claim of endorsement, review or approval by any source project. A
//     project whose data you used has not thereby blessed your product.
//   - No scholarly claim of any kind. Those belong to the qari gate and are
//     human-only forever.
//
// This is a copy module, not markup, for the same reason `lib/landing/copy.ts`
// is: strings that make claims are DATA, so they can be read by a test.

export interface AttributionSource {
  /** The project's own name for itself. */
  readonly name: string;
  /** What this product actually used it for — specific, never vague. */
  readonly used: string;
  /** The licence, named exactly as the project names it. */
  readonly licence: string;
  /** Canonical project URL. */
  readonly url: string;
  /** Named authors/maintainers, where the source names them. */
  readonly credit?: string;
  /** Anything a reader needs to correctly interpret the licence line. */
  readonly note?: string;
}

export const PAGE = {
  title: "Sources and attribution",
  lead:
    "This product is built on scholarly and open data prepared by other people. " +
    "Those projects are named here, with the licence each one carries and what " +
    "we actually used it for.",
  /** The honest framing of why the page exists at all. */
  standing:
    "We list these because attribution is a condition of using the work, not " +
    "because a page looked incomplete without it.",
} as const;

export const SOURCES: readonly AttributionSource[] = [
  {
    name: "The Quranic Arabic Corpus, version 0.4",
    credit: "Kais Dukes, University of Leeds",
    url: "https://corpus.quran.com/",
    licence: "GNU General Public License",
    used:
      "Word-by-word morphological analysis — lemma, root and part-of-speech — " +
      "used at build time to generate and validate the multiple-choice " +
      "distractors, and to check that every distractor is a word that actually " +
      "occurs in the Quran.",
    note:
      "These annotations are used when the corpus is compiled and are removed " +
      "before anything is sent to your browser. The morphology is not part of " +
      "the app you download.",
  },
  {
    name: "The Tanzil Project",
    url: "https://tanzil.net",
    licence:
      "Tanzil terms of use — the Quran text may be copied and distributed verbatim",
    used:
      "The Uthmani Quran text and the canonical ayah numbering. Every ayah " +
      "boundary and every ayah number in this product follows Tanzil's " +
      "numbering, including its structural marking of the basmalah.",
    note:
      "The Quran text itself carries no copyright claim by anyone. It is " +
      "reproduced verbatim and is never modified, paraphrased or generated.",
  },
] as const;

/**
 * The typefaces. Ship a webfont, name its licence — the same obligation, in a
 * smaller package, and the one most often skipped.
 */
export const FONTS: readonly AttributionSource[] = [
  {
    // Credit copied from the font's own `name` table (read 2026-08-11 and
    // recorded in public/fonts/FONTS.md), not from memory. The table credits
    // the project authors collectively; naming one individual would be a
    // guess, and a guess on an attribution page is a misattribution.
    name: "Amiri, version 0.113",
    credit: "Copyright 2010–2020 The Amiri Project Authors",
    url: "https://github.com/alif-type/amiri",
    licence: "SIL Open Font License, Version 1.1",
    used: "The Arabic typeface every ayah in this product is rendered in.",
  },
] as const;

/**
 * What the product does NOT claim. Stated on the page itself rather than left
 * to inference — a reader deciding whether to trust religious content deserves
 * to see the boundary drawn explicitly, and v3-D19 makes the same commitment on
 * the landing page.
 */
export const BOUNDARIES: readonly string[] = [
  "None of the projects listed here has reviewed, endorsed or approved this product.",
  "Listing a source is a statement about where data came from, never a claim of scholarly authority.",
  "The Quran text is reproduced verbatim from the source above. It is never generated, paraphrased or altered.",
] as const;

/** Where a reader goes with a correction. An attribution page with no route to
 *  a fix is a plaque, not a commitment. */
export const CORRECTIONS =
  "If any attribution here is wrong or incomplete, tell us and we will correct it.";

/**
 * Every attribution string, flat — the shape `lib/landing/copy.ts#landingStrings`
 * uses, so a test can read the page's claims as data instead of scraping markup.
 */
export function attributionStrings(): string[] {
  const out: string[] = [];
  const walk = (value: unknown): void => {
    if (typeof value === "string") {
      out.push(value);
      return;
    }
    if (Array.isArray(value)) {
      value.forEach(walk);
      return;
    }
    if (value && typeof value === "object") {
      Object.values(value).forEach(walk);
    }
  };
  walk([PAGE, SOURCES, FONTS, BOUNDARIES, CORRECTIONS]);
  return out;
}
