// Surah-keyed corpus loader (v2-D29: no hardcoded surah anywhere in the
// framework). Each surah's compiled corpus ships as its own static JSON at
// /corpus/<surah>.json (public/corpus/<surah>.json — regenerated by
// packages/corpus-compiler, ported from v1 unchanged for regen only). v2
// ships Yusuf (12) only; adding a surah later is a compiler run + a new file
// here, no code changes.

import type { Corpus } from "engine";

export class CorpusLoadError extends Error {}

/** Fetch + validate the compiled corpus for one surah. Pure IO, no caching. */
export async function loadCorpus(surah: number): Promise<Corpus> {
  const res = await fetch(`/corpus/${surah}.json`);
  if (!res.ok) {
    throw new CorpusLoadError(`corpus for surah ${surah}: HTTP ${res.status}`);
  }
  const corpus = (await res.json()) as Corpus;
  if (corpus.meta.surah !== surah) {
    throw new CorpusLoadError(
      `corpus for surah ${surah}: file reports surah ${corpus.meta.surah}`,
    );
  }
  return corpus;
}
