// output/<surah>/corpus-report.md — a human spot-check: validation summary +
// up to 10 seeded-random words with full morphology and their distractor
// sets, so the user can review linguistic quality. Deterministic (seeded
// LCG, no Math.random).
//
// Ported from v1/packages/corpus-compiler/src/report.ts, surah-parameterized:
// the title and sample seed now derive from the surah number instead of
// being hardcoded to Yusuf, and the sample size shrinks gracefully for
// degenerate surahs with fewer than 10 words (103 has 14, 112 has 15 — both
// still sample fine, but the code no longer assumes ≥10 exists).

import type { CorpusJson, Distractor, Word } from "./types.ts";
import type { ValidationReport } from "./validate.ts";

/** Mulberry32-style deterministic PRNG so the sample is stable across runs. */
function seededPick(count: number, max: number, seed: number): number[] {
  if (max <= 0) return [];
  let s = seed >>> 0;
  const next = (): number => {
    s |= 0;
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const picked = new Set<number>();
  while (picked.size < Math.min(count, max)) picked.add(Math.floor(next() * max));
  return [...picked].sort((a, b) => a - b);
}

export function buildReport(corpus: CorpusJson, validation: ValidationReport): string {
  const surah = corpus.meta.surah;
  const sampleSeed = surah * 1000 + corpus.meta.ayahCount; // deterministic, surah-distinct

  const distByWord = new Map<string, Distractor[]>();
  for (const d of corpus.distractors) {
    const k = `${d.ayah}:${d.position}`;
    let g = distByWord.get(k);
    if (!g) {
      g = [];
      distByWord.set(k, g);
    }
    g.push(d);
  }

  const idxs = seededPick(10, corpus.words.length, sampleSeed);
  const sample: Word[] = idxs.map((i) => corpus.words[i]!);

  const md: string[] = [];
  md.push(`# Corpus spot-check report — surah ${surah}`);
  md.push("");
  md.push(
    "Generated by `v3/packages/corpus-compiler`. Review the sampled words below " +
      "for linguistic quality (gloss, lemma/root/class, and distractor sets). " +
      "The sample is deterministic (seed " +
      `${sampleSeed}), so re-running the compiler produces the same rows.`,
  );
  md.push("");

  // Validation summary.
  md.push("## Validation summary");
  md.push("");
  md.push("| Check | Severity | Result | Detail |");
  md.push("|---|---|---|---|");
  for (const c of validation.checks) {
    const res = c.pass ? "✓ pass" : c.severity === "hard" ? "✗ FAIL" : "⚠ note";
    md.push(`| ${c.name} | ${c.severity} | ${res} | ${c.detail.replace(/\|/g, "\\|")} |`);
  }
  md.push("");
  md.push(`**Overall: ${validation.ok ? "PASS" : "FAIL"}**`);
  md.push("");

  // Dropped collisions.
  md.push("## Self-collisions dropped during compile");
  md.push("");
  if (corpus.meta.droppedCollisions.length === 0) {
    md.push("_None._");
  } else {
    md.push(
      "These items shipped 5 distractors, one of which equaled the target; the " +
        "colliding distractor was removed (leaving 4). Backfill a 5th when convenient.",
    );
    md.push("");
    md.push("| Ayah | Position | Target |");
    md.push("|---|---|---|");
    for (const c of corpus.meta.droppedCollisions) {
      const w = corpus.words.find((x) => x.ayah === c.ayah && x.position === c.position);
      md.push(`| ${c.ayah} | ${c.position} | ${w ? w.text_uthmani : ""} |`);
    }
  }
  md.push("");

  // Distractor attestation (soft review flag).
  const missing = validation.stats.missingFromQuran;
  md.push("## Distractors not attested verbatim in the mushaf");
  md.push("");
  if (corpus.distractors.length === 0) {
    md.push(
      "_No authored distractors for this surah (foil-kernel generation is separate, " +
        "not-yet-implemented follow-on work)._",
    );
  } else {
    md.push(
      `${missing.length} distinct distractor forms are morphologically-valid Arabic ` +
        "but do not occur in that exact surface form anywhere in the Quran. These are " +
        "strong pedagogical traps, not errors — flagged here for qari/teacher review. First 40:",
    );
    md.push("");
    md.push("> " + missing.slice(0, 40).join(" · "));
  }
  md.push("");

  // Morphology coverage note.
  const mc = validation.stats.morphCoverage;
  md.push("## Morphology coverage");
  md.push("");
  md.push(
    `lemma ${mc.lemma}/${mc.total}, root ${mc.root}/${mc.total}, class ${mc.class}/${mc.total}. ` +
      "Null lemma/root is expected for particles and proper nouns (QAC assigns them none).",
  );
  md.push("");

  // sampled words.
  md.push(`## ${sample.length} sampled words with distractor sets`);
  md.push("");
  for (const w of sample) {
    md.push(`### Ayah ${w.ayah}, position ${w.position} — ${w.text_uthmani}`);
    md.push("");
    md.push(`- **Gloss (EN):** ${w.gloss.en ?? "—"}`);
    md.push(
      `- **Morphology:** lemma ${w.lemma ?? "—"} · root ${w.root ?? "—"} · class ${w.class ?? "—"}`,
    );
    md.push(`- **Act:** ${w.act ?? "—"}`);
    md.push("");
    const ds = distByWord.get(`${w.ayah}:${w.position}`) ?? [];
    if (ds.length > 0) {
      md.push("| Rank | Distractor | PRD rank | Src type | Why |");
      md.push("|---|---|---|---|---|");
      for (const d of ds) {
        md.push(
          `| ${d.rank} | ${d.text} | ${d.prd_rank} | ${d.src_type} | ${d.why.replace(/\|/g, "\\|")} |`,
        );
      }
    } else {
      md.push("_No distractors for this word._");
    }
    md.push("");
  }

  md.push("---");
  md.push("");
  md.push(
    "_Scene-beat labels are TODO placeholders where unauthored. MS/JA glosses and " +
      "mushaf page/line are intentionally null (geometry merge is build-plan step 4)._",
  );
  md.push("");
  return md.join("\n");
}
